# Generated by Django 5.2.4 on 2026-09-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='手机号')),
                ('license_type', models.CharField(max_length=8, verbose_name='驾照类型')),
                ('license_expire_date', models.DateField(blank=True, null=True, verbose_name='驾照到期日')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('status', models.CharField(choices=[('Available', '可用'), ('OnTrip', '运输中'), ('Leave', '休假'), ('Suspended', '停职')], default='Available', max_length=24, verbose_name='当前状态')),
                ('driving_hours', models.IntegerField(default=0, verbose_name='累计驾驶时长(h)')),
                ('violation_count', models.IntegerField(default=0, verbose_name='违章次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=32, unique=True, verbose_name='车牌号')),
                ('vehicle_type', models.CharField(max_length=32, verbose_name='车辆类型')),
                ('brand_model', models.CharField(max_length=80, verbose_name='品牌型号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('insurance_expire_date', models.DateField(blank=True, null=True, verbose_name='保险到期日')),
                ('inspection_expire_date', models.DateField(blank=True, null=True, verbose_name='年检到期日')),
                ('status', models.CharField(choices=[('Available', '可用'), ('OnTrip', '运输中'), ('Maintenance', '维保中'), ('Retired', '已报废')], default='Available', max_length=24, verbose_name='当前状态')),
                ('mileage', models.IntegerField(default=0, verbose_name='累计里程(km)')),
                ('tank_capacity', models.FloatField(default=0, verbose_name='油箱容量(L)')),
                ('payload_capacity', models.FloatField(default=0, verbose_name='额定载重(kg)')),
                ('fuel_consumption', models.FloatField(default=0, verbose_name='当前油耗(L/100km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Routine', '常规保养'), ('Repair', '维修'), ('Emergency', '紧急维修'), ('Inspection', '年检')], max_length=24)),
                ('items', models.JSONField(blank=True, default=list)),
                ('cost', models.FloatField(default=0, verbose_name='维修费用')),
                ('vendor', models.CharField(blank=True, default='', max_length=120, verbose_name='维修厂')),
                ('date', models.DateField(blank=True, null=True, verbose_name='维修日期')),
                ('next_mileage', models.IntegerField(default=0, verbose_name='下次保养里程')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='下次保养日期')),
                ('status', models.CharField(choices=[('Scheduled', '已计划'), ('InProgress', '进行中'), ('Completed', '已完成')], default='Scheduled', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet_app.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='加油日期')),
                ('liters', models.FloatField(default=0, verbose_name='加油量(L)')),
                ('unit_price', models.FloatField(default=0, verbose_name='单价')),
                ('total_amount', models.FloatField(default=0, verbose_name='总金额')),
                ('mileage', models.IntegerField(default=0, verbose_name='当前里程')),
                ('station', models.CharField(blank=True, default='', max_length=120, verbose_name='加油站')),
                ('payment_method', models.CharField(choices=[('Cash', '现金'), ('Card', '油卡'), ('Company', '公司结算')], default='Company', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='fleet_app.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40, unique=True, verbose_name='单号')),
                ('origin', models.CharField(max_length=120, verbose_name='出发地')),
                ('destination', models.CharField(max_length=120, verbose_name='目的地')),
                ('plan_depart_at', models.DateTimeField(blank=True, null=True, verbose_name='预计出发时间')),
                ('plan_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间')),
                ('actual_depart_at', models.DateTimeField(blank=True, null=True, verbose_name='实际出发时间')),
                ('actual_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='实际到达时间')),
                ('cargo', models.CharField(blank=True, default='', max_length=160, verbose_name='货物描述')),
                ('weight', models.FloatField(default=0, verbose_name='重量(kg)')),
                ('freight', models.FloatField(default=0, verbose_name='运费')),
                ('status', models.CharField(choices=[('Pending', '待指派'), ('Assigned', '已指派'), ('InProgress', '运输中'), ('Completed', '已完成'), ('Cancelled', '已取消')], default='Assigned', max_length=24, verbose_name='状态')),
                ('creator_id', models.IntegerField(default=1, verbose_name='创建人ID')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='指派时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始运输时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to='fleet_app.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to='fleet_app.vehicle')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Created', '创建调度单'), ('Assigned', '指派车辆与司机'), ('Reassigned', '改派'), ('Started', '开始运输'), ('Completed', '完成运输'), ('Cancelled', '取消调度单')], max_length=24)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(blank=True, default='', max_length=24)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('operator_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet_app.dispatchorder')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order', 'id'], name='fleet_app_d_order_i_03edb4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dispatchorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Assigned', 'InProgress'])), fields=('vehicle',), name='uniq_active_dispatch_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='dispatchorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Assigned', 'InProgress'])), fields=('driver',), name='uniq_active_dispatch_per_driver'),
        ),
    ]
